### ISSUE TITLE
[ERROR] Error handling request /api/users/

### ISSUE THREAD

**Issue by stryker09** [dwang159/oncall-admin#8]
Probably related to the latest oncall commits, none of the functions no longer seem to work:

> [2019-03-30 14:35:36 +0000] [7155] [ERROR] Error handling request /api/users/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/falcon-1.1.0-py2.7.egg/falcon/api.py", line 209, in __call__
    responder(req, resp, **params)
  File "/home/stryker/develop/oncall-admin/src/oncall_admin/api.py", line 88, in on_post
    connection = db.engine.raw_connection()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.2-py2.7.egg/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.2-py2.7.egg/pymysql/connections.py", line 679, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.2-py2.7.egg/pymysql/connections.py", line 890, in connect
    self._get_server_information()
  File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.2-py2.7.egg/pymysql/connections.py", line 1214, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.2-py2.7.egg/pymysql/charset.py", line 34, in by_id
    return self._by_id[id]
KeyError: 255
172.18.100.65 - - [30/Mar/2019:14:35:36 +0800] "POST /api/users/ HTTP/1.1" 500 0 "-" "-"

**Comment by dwang159** [comment]
This is probably an issue with our version of PyMySQL and MySQL 8.0. You
can try bumping the PyMySQL version and see if that fixes the issue.
Otherwise, switching to 5.7 will likely fix it.
